// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOX9-vt0tJF0GK0gy7BAP2jGgF2ErtYDQ',
    appId: '1:29374283926:web:d61024dbc7394f863542b7',
    messagingSenderId: '29374283926',
    projectId: 'aezakmitesttask-1f0ed',
    authDomain: 'aezakmitesttask-1f0ed.firebaseapp.com',
    storageBucket: 'aezakmitesttask-1f0ed.firebasestorage.app',
    measurementId: 'G-XQPXY7ZDSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfx7lSPhJUgATTLRySU-z8wZQ-wSl2VNk',
    appId: '1:29374283926:android:f5b1fb29d654ebd33542b7',
    messagingSenderId: '29374283926',
    projectId: 'aezakmitesttask-1f0ed',
    storageBucket: 'aezakmitesttask-1f0ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChhwfHVI9i4eV1TBfmFNFoVA91HlsOR50',
    appId: '1:29374283926:ios:88a84c8d01e7500d3542b7',
    messagingSenderId: '29374283926',
    projectId: 'aezakmitesttask-1f0ed',
    storageBucket: 'aezakmitesttask-1f0ed.firebasestorage.app',
    iosBundleId: 'com.example.aezakmiTestTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChhwfHVI9i4eV1TBfmFNFoVA91HlsOR50',
    appId: '1:29374283926:ios:88a84c8d01e7500d3542b7',
    messagingSenderId: '29374283926',
    projectId: 'aezakmitesttask-1f0ed',
    storageBucket: 'aezakmitesttask-1f0ed.firebasestorage.app',
    iosBundleId: 'com.example.aezakmiTestTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOX9-vt0tJF0GK0gy7BAP2jGgF2ErtYDQ',
    appId: '1:29374283926:web:a80c402ceb2099a43542b7',
    messagingSenderId: '29374283926',
    projectId: 'aezakmitesttask-1f0ed',
    authDomain: 'aezakmitesttask-1f0ed.firebaseapp.com',
    storageBucket: 'aezakmitesttask-1f0ed.firebasestorage.app',
    measurementId: 'G-K4B245J7ZD',
  );
}